name: QA

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  QA:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ''
      - run: |
          git fetch --prune --unshallow
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: SonarCloud Scan
        set environment variables:
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run sonar maven plugin:
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=OneS_ClusterAdmin -Dsonar.organization=YanSergey -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN